###
# Mongo Shell: docker exec -it mongo mongosh
###
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.data:/data/db
    restart: always