[project]
name = "uv-task-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask-pymongo>=3.0.1",
    "flask>=3.1.0",
    "pymongo>=4.12.0",
]
